## Homework 6 Data Cleaning 

###  DatasET  : NYPD Motor Vehicle Collisions
This is a breakdown of every collision in NYC by location and injury. This data is collected because the NYC Council passed Local Law #11 in 2011. This data is manually run every month and reviewed by the TrafficStat Unit before being posted on the NYPD website. Each record represents a collision in NYC by city, borough, precinct and cross street. This data can be used by the public to see how dangerous/safe intersections are in NYC. The information is presented in pdf and excel format to allow the casual user to just view the information in the easy to read pdf format or use the excel files to do a more in-depth analysis.

### Dataset link : https://data.cityofnewyork.us/Public-Safety/NYPD-Motor-Vehicle-Collisions/h9gi-nx95/data


### Goals : To clean the dataset by eliminating NaN values , droping NA columns , parsing Dates,etc

##  Importing Dataset

In [4]:
import pandas as pd

Importing the CSV file of the dataset and storing it in dataframe named "data"

In [15]:
data = pd.read_csv("C:/Users/akhil/Desktop/MITA SEM 1/Intro to Data Science/Homework/Data Cleaning/NYPD_Motor_Vehicle_Collisions.csv")

C:\Users\akhil\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
print(data.shape) # size of dataset

(1360317, 29)

In [19]:
data.head() # data cols and rows

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,471 KEAP STREET,...,Unspecified,NaN,NaN,NaN,3996168,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,4212 HIGHLAND AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,157 WEST 47 STREET,...,Unspecified,NaN,NaN,NaN,3997603,Sedan,Taxi,NaN,NaN,NaN
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996194,Sedan,Sedan,NaN,NaN,NaN
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,3 AVENUE,...,Unspecified,NaN,NaN,NaN,3995663,Taxi,Pick-up Truck,NaN,NaN,NaN

In [21]:
data.index

RangeIndex(start=0, stop=1360317, step=1)

In [24]:
data.columns # Names of the Columns

Index(['DATE', 'TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE', 'LONGITUDE',
       'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME', 'OFF STREET NAME',
       'NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED',
       'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED',
       'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED',
       'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED',
       'CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2',
       'CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4',
       'CONTRIBUTING FACTOR VEHICLE 5', 'UNIQUE KEY', 'VEHICLE TYPE CODE 1',
       'VEHICLE TYPE CODE 2', 'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4',
       'VEHICLE TYPE CODE 5'],
      dtype='object')

### Retriving all the null values from the data

In [26]:
print(data.isnull().head())

    DATE   TIME  BOROUGH  ZIP CODE  LATITUDE  LONGITUDE  LOCATION  \
0  False  False    False     False     False      False     False
1  False  False    False     False     False      False     False
2  False  False    False     False     False      False     False
3  False  False     True      True     False      False     False
4  False  False     True      True     False      False     False

   ON STREET NAME  CROSS STREET NAME  OFF STREET NAME         ...           \
0            True               True            False         ...
1            True               True            False         ...
2            True               True            False         ...
3           False               True             True         ...
4            True               True            False         ...

   CONTRIBUTING FACTOR VEHICLE 2  CONTRIBUTING FACTOR VEHICLE 3  \
0                          False                           True
1                          False                           True
2                          False                           True
3                          False                           True
4                          False                           True

   CONTRIBUTING FACTOR VEHICLE 4  CONTRIBUTING FACTOR VEHICLE 5  UNIQUE KEY  \
0                           True                           True       False
1                           True                           True       False
2                           True                           True       False
3                           True                           True       False
4                           True                           True       False

   VEHICLE TYPE CODE 1  VEHICLE TYPE CODE 2  VEHICLE TYPE CODE 3  \
0                False                False                 True
1                False                False                 True
2                False                False                 True
3                False                False                 True
4                False                False                 True

   VEHICLE TYPE CODE 4  VEHICLE TYPE CODE 5
0                 True                 True
1                 True                 True
2                 True                 True
3                 True                 True
4                 True                 True

[5 rows x 29 columns]

In [89]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,471 KEAP STREET,...,Unspecified,NaN,NaN,NaN,3996168,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,4212 HIGHLAND AVENUE,...,Driver Inattention/Distraction,NaN,NaN,NaN,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,157 WEST 47 STREET,...,Unspecified,NaN,NaN,NaN,3997603,Sedan,Taxi,NaN,NaN,NaN
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996194,Sedan,Sedan,NaN,NaN,NaN
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,3 AVENUE,...,Unspecified,NaN,NaN,NaN,3995663,Taxi,Pick-up Truck,NaN,NaN,NaN
5,10/08/2018,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,NaN,...,Unsafe Speed,NaN,NaN,NaN,3996499,Sedan,Sedan,NaN,NaN,NaN
6,10/08/2018,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996010,Sedan,NaN,NaN,NaN,NaN
7,10/08/2018,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,NaN,...,Unspecified,NaN,NaN,NaN,3995363,Taxi,Bike,NaN,NaN,NaN
8,10/08/2018,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3996597,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
9,10/08/2018,0:17,NaN,NaN,NaN,NaN,NaN,BROOKLYN QUEENS EXPRESSWAY RAMP,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3996027,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
10,10/08/2018,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,NaN,...,Unspecified,Unspecified,Unspecified,NaN,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN
11,10/08/2018,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,NaN,...,NaN,NaN,NaN,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
12,10/08/2018,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
13,10/08/2018,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,2070 7 AVENUE,...,Unspecified,NaN,NaN,NaN,3995721,Sedan,Taxi,NaN,NaN,NaN
14,10/08/2018,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3995990,Sedan,NaN,NaN,NaN,NaN
15,10/08/2018,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3997540,Sedan,Sedan,NaN,NaN,NaN
16,10/08/2018,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,3997169,Station Wagon/Sport Utility Vehicle,Dump,NaN,NaN,NaN
17,10/08/2018,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,59-08 157 STREET,...,NaN,NaN,NaN,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
18,10/08/2018,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,3996058,Sedan,Sedan,NaN,NaN,NaN
19,10/08/2018,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996567,Dump,Sedan,NaN,NaN,NaN
20,10/08/2018,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
21,10/08/2018,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996206,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
22,10/08/2018,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996726,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
23,10/08/2018,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3996522,Sedan,Sedan,NaN,NaN,NaN
24,10/08/2018,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,NaN,...,Unspecified,NaN,NaN,NaN,3995978,Sedan,Ambulance,NaN,NaN,NaN
25,10/08/2018,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,3996343,Box Truck,Sedan,NaN,NaN,NaN
26,10/08/2018,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3996777,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
27,10/08/2018,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,1665 43 STREET,...,Unspecified,NaN,NaN,NaN,3996177,Box Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
28,10/08/2018,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3996251,Sedan,Sedan,NaN,NaN,NaN
29,10/08/2018,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,87-47 118 STREET,...,Driver Inattention/Distraction,NaN,NaN,NaN,3996216,Sedan,Sedan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360287,07/01/2012,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,179414,PASSENGER VEHICLE,LIVERY VEHICLE,NaN,NaN,NaN
1360288,07/01/2012,8:27,NaN,NaN,40.708797,-73.727620,"(40.7087971, -73.72762)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3016724,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
1360289,07/01/2012,8:30,NaN,NaN,NaN,NaN,NaN,WEST 181 STREET,RIVERSIDE DRIVE,NaN,...,NaN,NaN,NaN,NaN,70031,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
1360290,07/01/2012,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,172551,PASSENGER VEHICLE,VAN,NaN,NaN,NaN
1360291,07/01/2012,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,NaN,...,NaN,NaN,NaN,NaN,208724,UNKNOWN,NaN,NaN,NaN,NaN
1360292,07/01/2012,8:43,NaN,NaN,NaN,NaN,NaN,HORACE HARDING EXPRESSWAY,UTOPIA PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,233142,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
1360293,07/01/2012,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,NaN,...,Unspecified,NaN,NaN,NaN,94868,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
1360294,07/01/2012,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360295,07/01/2012,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,NaN,...,NaN,NaN,NaN,NaN,37634,TAXI,NaN,NaN,NaN,NaN
1360296,07/01/2012,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,NaN,...,Unspecified,NaN,NaN,NaN,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360297,07/01/2012,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,203690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1360298,07/01/2012,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,219394,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
1360299,07/01/2012,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,284646,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1360300,07/01/2012,9:20,NaN,NaN,NaN,NaN,NaN,FOOD CENTER DRIVE,HALLECK STREET,NaN,...,NaN,NaN,NaN,NaN,76204,LARGE COM VEH(6 OR MORE TIRES),NaN,NaN,NaN,NaN
1360301,07/01/2012,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,NaN,...,Unspecified,NaN,NaN,NaN,219398,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
1360302,07/01/2012,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,NaN,...,Unspecified,NaN,NaN,NaN,88535,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
1360303,07/01/2012,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,129899,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
1360304,07/01/2012,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,254997,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
1360305,07/01/2012,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
1360306,07/01/2012,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
1360307,07/01/2012,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,NaN,...,Unspecified,NaN,NaN,NaN,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360308,07/01/2012,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,NaN,...,Driver Inexperience,NaN,NaN,NaN,5294,PASSENGER VEHICLE,LIVERY VEHICLE,NaN,NaN,NaN
1360309,07/01/2012,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,NaN,...,Unspecified,NaN,NaN,NaN,245559,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1360310,07/01/2012,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,NaN,...,Unspecified,NaN,NaN,NaN,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360311,07/01/2012,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,NaN,...,Unspecified,NaN,NaN,NaN,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
1360312,07/01/2012,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2896726,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN
1360313,07/01/2012,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,NaN,...,Unspecified,NaN,NaN,NaN,37635,VAN,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360314,07/01/2012,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1360315,07/01/2012,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,NaN,...,Other Vehicular,NaN,NaN,NaN,44907,PASSENGER VEHICLE,TAXI,NaN,NaN,NaN
1360316,07/01/2012,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN

**Looking into the NULL values data in df getting the SUM of these null values with each column**

In [90]:
print(data.isnull().sum())

DATE                                   0
TIME                                   0
BOROUGH                           397642
ZIP CODE                          397766
LATITUDE                          224304
LONGITUDE                         224304
LOCATION                          224304
ON STREET NAME                    273211
CROSS STREET NAME                 375723
OFF STREET NAME                  1135465
NUMBER OF PERSONS INJURED              0
NUMBER OF PERSONS KILLED               0
NUMBER OF PEDESTRIANS INJURED          0
NUMBER OF PEDESTRIANS KILLED           0
NUMBER OF CYCLIST INJURED              0
NUMBER OF CYCLIST KILLED               0
NUMBER OF MOTORIST INJURED             0
NUMBER OF MOTORIST KILLED              0
CONTRIBUTING FACTOR VEHICLE 1       7315
CONTRIBUTING FACTOR VEHICLE 2     196019
CONTRIBUTING FACTOR VEHICLE 3    1272670
CONTRIBUTING FACTOR VEHICLE 4    1341525
CONTRIBUTING FACTOR VEHICLE 5    1355639
UNIQUE KEY                             0
VEHICLE TYPE CODE 1                10861
VEHICLE TYPE CODE 2               216099
VEHICLE TYPE CODE 3              1242834
VEHICLE TYPE CODE 4              1314175
VEHICLE TYPE CODE 5              1350553
dtype: int64

**Retriving the Not NULL values in each columns **

In [91]:
print(data.notnull().sum())

DATE                             1360317
TIME                             1360317
BOROUGH                           962675
ZIP CODE                          962551
LATITUDE                         1136013
LONGITUDE                        1136013
LOCATION                         1136013
ON STREET NAME                   1087106
CROSS STREET NAME                 984594
OFF STREET NAME                   224852
NUMBER OF PERSONS INJURED        1360317
NUMBER OF PERSONS KILLED         1360317
NUMBER OF PEDESTRIANS INJURED    1360317
NUMBER OF PEDESTRIANS KILLED     1360317
NUMBER OF CYCLIST INJURED        1360317
NUMBER OF CYCLIST KILLED         1360317
NUMBER OF MOTORIST INJURED       1360317
NUMBER OF MOTORIST KILLED        1360317
CONTRIBUTING FACTOR VEHICLE 1    1353002
CONTRIBUTING FACTOR VEHICLE 2    1164298
CONTRIBUTING FACTOR VEHICLE 3      87647
CONTRIBUTING FACTOR VEHICLE 4      18792
CONTRIBUTING FACTOR VEHICLE 5       4678
UNIQUE KEY                       1360317
VEHICLE TYPE CODE 1              1349456
VEHICLE TYPE CODE 2              1144218
VEHICLE TYPE CODE 3               117483
VEHICLE TYPE CODE 4                46142
VEHICLE TYPE CODE 5                 9764
dtype: int64

** Here Each columns with less than 1000 records are being dropped
since it wilhave no impact in series due to lack of information.**

In [98]:
for column in data:
    if(data[column].count() < 500000):
        data.drop([column],axis = 1 , inplace=True)

*Now we are left with the columns with less NaN values :)*<br>
**We have reduced columns from 29 to 22**

In [99]:
print(data.notnull().sum())

DATE                             1360317
TIME                             1360317
BOROUGH                           962675
ZIP CODE                          962551
LATITUDE                         1136013
LONGITUDE                        1136013
LOCATION                         1136013
ON STREET NAME                   1087106
CROSS STREET NAME                 984594
NUMBER OF PERSONS INJURED        1360317
NUMBER OF PERSONS KILLED         1360317
NUMBER OF PEDESTRIANS INJURED    1360317
NUMBER OF PEDESTRIANS KILLED     1360317
NUMBER OF CYCLIST INJURED        1360317
NUMBER OF CYCLIST KILLED         1360317
NUMBER OF MOTORIST INJURED       1360317
NUMBER OF MOTORIST KILLED        1360317
CONTRIBUTING FACTOR VEHICLE 1    1353002
CONTRIBUTING FACTOR VEHICLE 2    1164298
UNIQUE KEY                       1360317
VEHICLE TYPE CODE 1              1349456
VEHICLE TYPE CODE 2              1144218
dtype: int64

In [100]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,NUMBER OF PERSONS INJURED,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996168,Sedan,Station Wagon/Sport Utility Vehicle
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,0,...,0,0,0,0,0,Other Vehicular,Unspecified,3997603,Sedan,Taxi
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996194,Sedan,Sedan
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,0,...,0,0,0,0,0,Following Too Closely,Unspecified,3995663,Taxi,Pick-up Truck
5,10/08/2018,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,1,...,0,0,0,1,0,Traffic Control Disregarded,Unsafe Speed,3996499,Sedan,Sedan
6,10/08/2018,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996010,Sedan,NaN
7,10/08/2018,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,1,...,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,3995363,Taxi,Bike
8,10/08/2018,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3996597,Station Wagon/Sport Utility Vehicle,Sedan
9,10/08/2018,0:17,NaN,NaN,NaN,NaN,NaN,BROOKLYN QUEENS EXPRESSWAY RAMP,NaN,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,3996027,Station Wagon/Sport Utility Vehicle,Taxi
10,10/08/2018,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle
11,10/08/2018,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,0,...,0,0,0,0,0,Unspecified,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN
12,10/08/2018,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
13,10/08/2018,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3995721,Sedan,Taxi
14,10/08/2018,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995990,Sedan,NaN
15,10/08/2018,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3997540,Sedan,Sedan
16,10/08/2018,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997169,Station Wagon/Sport Utility Vehicle,Dump
17,10/08/2018,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN
18,10/08/2018,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3996058,Sedan,Sedan
19,10/08/2018,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3996567,Dump,Sedan
20,10/08/2018,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,1,...,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
21,10/08/2018,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,0,...,0,0,0,0,0,Reaction to Uninvolved Vehicle,Unspecified,3996206,Station Wagon/Sport Utility Vehicle,Sedan
22,10/08/2018,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,1,...,0,0,0,1,0,Following Too Closely,Unspecified,3996726,Sedan,Station Wagon/Sport Utility Vehicle
23,10/08/2018,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996522,Sedan,Sedan
24,10/08/2018,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,3995978,Sedan,Ambulance
25,10/08/2018,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996343,Box Truck,Sedan
26,10/08/2018,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,1,...,0,0,0,1,0,Turning Improperly,Unspecified,3996777,Sedan,Station Wagon/Sport Utility Vehicle
27,10/08/2018,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996177,Box Truck,Station Wagon/Sport Utility Vehicle
28,10/08/2018,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,3996251,Sedan,Sedan
29,10/08/2018,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,0,...,0,0,0,0,0,Unsafe Speed,Driver Inattention/Distraction,3996216,Sedan,Sedan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360287,07/01/2012,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,179414,PASSENGER VEHICLE,LIVERY VEHICLE
1360288,07/01/2012,8:27,NaN,NaN,40.708797,-73.727620,"(40.7087971, -73.72762)",NaN,NaN,2,...,0,0,0,2,0,Traffic Control Disregarded,NaN,3016724,PASSENGER VEHICLE,NaN
1360289,07/01/2012,8:30,NaN,NaN,NaN,NaN,NaN,WEST 181 STREET,RIVERSIDE DRIVE,0,...,0,0,0,0,0,Unspecified,NaN,70031,PASSENGER VEHICLE,NaN
1360290,07/01/2012,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,2,...,0,0,0,2,0,Unspecified,Unspecified,172551,PASSENGER VEHICLE,VAN
1360291,07/01/2012,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,1,...,0,0,0,0,0,Unspecified,NaN,208724,UNKNOWN,NaN
1360292,07/01/2012,8:43,NaN,NaN,NaN,NaN,NaN,HORACE HARDING EXPRESSWAY,UTOPIA PARKWAY,0,...,0,0,0,0,0,Fatigued/Drowsy,Unspecified,233142,PASSENGER VEHICLE,TAXI
1360293,07/01/2012,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,94868,SPORT UTILITY / STATION WAGON,UNKNOWN
1360294,07/01/2012,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360295,07/01/2012,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,1,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,37634,TAXI,NaN
1360296,07/01/2012,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,0,...,0,0,0,0,0,Unspecified,Unspecified,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
1360297,07/01/2012,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,0,...,0,0,0,0,0,Failure to Keep Right,Unspecified,203690,PASSENGER VEHICLE,PASSENGER VEHICLE
1360298,07/01/2012,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,219394,PASSENGER VEHICLE,UNKNOWN
1360299,07/01/2012,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,284646,PASSENGER VEHICLE,PASSENGER VEHICLE
1360300,07/01/2012,9:20,NaN,NaN,NaN,NaN,NaN,FOOD CENTER DRIVE,HALLECK STREET,0,...,0,0,0,0,0,Unspecified,NaN,76204,LARGE COM VEH(6 OR MORE TIRES),NaN
1360301,07/01/2012,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219398,PASSENGER VEHICLE,UNKNOWN
1360302,07/01/2012,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,0,...,0,0,0,0,0,Unspecified,Unspecified,88535,PASSENGER VEHICLE,UNKNOWN
1360303,07/01/2012,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,129899,PASSENGER VEHICLE,UNKNOWN
1360304,07/01/2012,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,254997,PASSENGER VEHICLE,PASSENGER VEHICLE
1360305,07/01/2012,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,1,...,0,0,0,1,0,Unspecified,Unspecified,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360306,07/01/2012,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360307,07/01/2012,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360308,07/01/2012,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,0,...,0,0,0,0,0,Driver Inexperience,Driver Inexperience,5294,PASSENGER VEHICLE,LIVERY VEHICLE
1360309,07/01/2012,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,245559,PASSENGER VEHICLE,PASSENGER VEHICLE
1360310,07/01/2012,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON
1360311,07/01/2012,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360312,07/01/2012,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,2896726,PASSENGER VEHICLE,UNKNOWN
1360313,07/01/2012,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,37635,VAN,SPORT UTILITY / STATION WAGON
1360314,07/01/2012,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,0,...,0,0,0,0,0,View Obstructed/Limited,Unspecified,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360315,07/01/2012,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,44907,PASSENGER VEHICLE,TAXI
1360316,07/01/2012,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,0,...,0,0,0,0,0,Glare,Unspecified,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON

###  Filling NaN values with 0 for Interger values columns like 
NUMBER OF PERSONS INJURED        
NUMBER OF PERSONS KILLED         
NUMBER OF PEDESTRIANS INJURED    
NUMBER OF PEDESTRIANS KILLED     
NUMBER OF CYCLIST INJURED        
NUMBER OF CYCLIST KILLED         
NUMBER OF MOTORIST INJURED       
NUMBER OF MOTORIST KILLED

In [101]:
data['NUMBER OF PERSONS INJURED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF PERSONS INJURED, dtype: int64

In [102]:
data['NUMBER OF PERSONS KILLED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF PERSONS KILLED, dtype: int64

In [75]:
df['NUMBER OF PEDESTRIANS INJURED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF PEDESTRIANS INJURED, dtype: int64

In [103]:
data['NUMBER OF PEDESTRIANS KILLED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF PEDESTRIANS KILLED, dtype: int64

In [77]:
df['NUMBER OF CYCLIST INJURED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF CYCLIST INJURED, dtype: int64

In [104]:
data['NUMBER OF CYCLIST KILLED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF CYCLIST KILLED, dtype: int64

In [105]:
data['NUMBER OF MOTORIST INJURED'].fillna(0).head()

0    0
1    0
2    0
3    0
4    0
Name: NUMBER OF MOTORIST INJURED, dtype: int64

In [106]:
data['NUMBER OF MOTORIST KILLED'].fillna(0).tail()

1360312    0
1360313    0
1360314    0
1360315    0
1360316    0
Name: NUMBER OF MOTORIST KILLED, dtype: int64

In [107]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,NUMBER OF PERSONS INJURED,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996168,Sedan,Station Wagon/Sport Utility Vehicle
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,0,...,0,0,0,0,0,Other Vehicular,Unspecified,3997603,Sedan,Taxi
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996194,Sedan,Sedan
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,0,...,0,0,0,0,0,Following Too Closely,Unspecified,3995663,Taxi,Pick-up Truck
5,10/08/2018,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,1,...,0,0,0,1,0,Traffic Control Disregarded,Unsafe Speed,3996499,Sedan,Sedan
6,10/08/2018,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996010,Sedan,NaN
7,10/08/2018,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,1,...,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,3995363,Taxi,Bike
8,10/08/2018,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3996597,Station Wagon/Sport Utility Vehicle,Sedan
9,10/08/2018,0:17,NaN,NaN,NaN,NaN,NaN,BROOKLYN QUEENS EXPRESSWAY RAMP,NaN,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,3996027,Station Wagon/Sport Utility Vehicle,Taxi
10,10/08/2018,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle
11,10/08/2018,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,0,...,0,0,0,0,0,Unspecified,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN
12,10/08/2018,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
13,10/08/2018,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3995721,Sedan,Taxi
14,10/08/2018,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995990,Sedan,NaN
15,10/08/2018,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3997540,Sedan,Sedan
16,10/08/2018,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997169,Station Wagon/Sport Utility Vehicle,Dump
17,10/08/2018,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN
18,10/08/2018,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3996058,Sedan,Sedan
19,10/08/2018,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3996567,Dump,Sedan
20,10/08/2018,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,1,...,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
21,10/08/2018,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,0,...,0,0,0,0,0,Reaction to Uninvolved Vehicle,Unspecified,3996206,Station Wagon/Sport Utility Vehicle,Sedan
22,10/08/2018,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,1,...,0,0,0,1,0,Following Too Closely,Unspecified,3996726,Sedan,Station Wagon/Sport Utility Vehicle
23,10/08/2018,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996522,Sedan,Sedan
24,10/08/2018,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,3995978,Sedan,Ambulance
25,10/08/2018,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996343,Box Truck,Sedan
26,10/08/2018,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,1,...,0,0,0,1,0,Turning Improperly,Unspecified,3996777,Sedan,Station Wagon/Sport Utility Vehicle
27,10/08/2018,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996177,Box Truck,Station Wagon/Sport Utility Vehicle
28,10/08/2018,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,3996251,Sedan,Sedan
29,10/08/2018,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,0,...,0,0,0,0,0,Unsafe Speed,Driver Inattention/Distraction,3996216,Sedan,Sedan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360287,07/01/2012,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,179414,PASSENGER VEHICLE,LIVERY VEHICLE
1360288,07/01/2012,8:27,NaN,NaN,40.708797,-73.727620,"(40.7087971, -73.72762)",NaN,NaN,2,...,0,0,0,2,0,Traffic Control Disregarded,NaN,3016724,PASSENGER VEHICLE,NaN
1360289,07/01/2012,8:30,NaN,NaN,NaN,NaN,NaN,WEST 181 STREET,RIVERSIDE DRIVE,0,...,0,0,0,0,0,Unspecified,NaN,70031,PASSENGER VEHICLE,NaN
1360290,07/01/2012,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,2,...,0,0,0,2,0,Unspecified,Unspecified,172551,PASSENGER VEHICLE,VAN
1360291,07/01/2012,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,1,...,0,0,0,0,0,Unspecified,NaN,208724,UNKNOWN,NaN
1360292,07/01/2012,8:43,NaN,NaN,NaN,NaN,NaN,HORACE HARDING EXPRESSWAY,UTOPIA PARKWAY,0,...,0,0,0,0,0,Fatigued/Drowsy,Unspecified,233142,PASSENGER VEHICLE,TAXI
1360293,07/01/2012,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,94868,SPORT UTILITY / STATION WAGON,UNKNOWN
1360294,07/01/2012,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360295,07/01/2012,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,1,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,37634,TAXI,NaN
1360296,07/01/2012,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,0,...,0,0,0,0,0,Unspecified,Unspecified,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
1360297,07/01/2012,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,0,...,0,0,0,0,0,Failure to Keep Right,Unspecified,203690,PASSENGER VEHICLE,PASSENGER VEHICLE
1360298,07/01/2012,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,219394,PASSENGER VEHICLE,UNKNOWN
1360299,07/01/2012,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,284646,PASSENGER VEHICLE,PASSENGER VEHICLE
1360300,07/01/2012,9:20,NaN,NaN,NaN,NaN,NaN,FOOD CENTER DRIVE,HALLECK STREET,0,...,0,0,0,0,0,Unspecified,NaN,76204,LARGE COM VEH(6 OR MORE TIRES),NaN
1360301,07/01/2012,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219398,PASSENGER VEHICLE,UNKNOWN
1360302,07/01/2012,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,0,...,0,0,0,0,0,Unspecified,Unspecified,88535,PASSENGER VEHICLE,UNKNOWN
1360303,07/01/2012,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,129899,PASSENGER VEHICLE,UNKNOWN
1360304,07/01/2012,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,254997,PASSENGER VEHICLE,PASSENGER VEHICLE
1360305,07/01/2012,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,1,...,0,0,0,1,0,Unspecified,Unspecified,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360306,07/01/2012,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360307,07/01/2012,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360308,07/01/2012,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,0,...,0,0,0,0,0,Driver Inexperience,Driver Inexperience,5294,PASSENGER VEHICLE,LIVERY VEHICLE
1360309,07/01/2012,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,245559,PASSENGER VEHICLE,PASSENGER VEHICLE
1360310,07/01/2012,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON
1360311,07/01/2012,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360312,07/01/2012,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,2896726,PASSENGER VEHICLE,UNKNOWN
1360313,07/01/2012,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,37635,VAN,SPORT UTILITY / STATION WAGON
1360314,07/01/2012,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,0,...,0,0,0,0,0,View Obstructed/Limited,Unspecified,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360315,07/01/2012,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,44907,PASSENGER VEHICLE,TAXI
1360316,07/01/2012,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,0,...,0,0,0,0,0,Glare,Unspecified,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON

### Dropping Rows not having atleast 18 real values or having 4 NaN values 
BY  setting Thres value in dropna to 18 means that out of 22 columns there should be atleast 18 columns that should have real values.

In [110]:
data.dropna(thresh=18 ,inplace=True)

In [111]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,NUMBER OF PERSONS INJURED,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996168,Sedan,Station Wagon/Sport Utility Vehicle
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,0,...,0,0,0,0,0,Other Vehicular,Unspecified,3997603,Sedan,Taxi
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996194,Sedan,Sedan
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,0,...,0,0,0,0,0,Following Too Closely,Unspecified,3995663,Taxi,Pick-up Truck
5,10/08/2018,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,1,...,0,0,0,1,0,Traffic Control Disregarded,Unsafe Speed,3996499,Sedan,Sedan
6,10/08/2018,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996010,Sedan,NaN
7,10/08/2018,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,1,...,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,3995363,Taxi,Bike
8,10/08/2018,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3996597,Station Wagon/Sport Utility Vehicle,Sedan
10,10/08/2018,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle
11,10/08/2018,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,0,...,0,0,0,0,0,Unspecified,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN
12,10/08/2018,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
13,10/08/2018,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3995721,Sedan,Taxi
14,10/08/2018,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995990,Sedan,NaN
15,10/08/2018,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3997540,Sedan,Sedan
16,10/08/2018,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997169,Station Wagon/Sport Utility Vehicle,Dump
17,10/08/2018,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN
18,10/08/2018,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3996058,Sedan,Sedan
19,10/08/2018,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3996567,Dump,Sedan
20,10/08/2018,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,1,...,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
21,10/08/2018,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,0,...,0,0,0,0,0,Reaction to Uninvolved Vehicle,Unspecified,3996206,Station Wagon/Sport Utility Vehicle,Sedan
22,10/08/2018,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,1,...,0,0,0,1,0,Following Too Closely,Unspecified,3996726,Sedan,Station Wagon/Sport Utility Vehicle
23,10/08/2018,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996522,Sedan,Sedan
24,10/08/2018,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,3995978,Sedan,Ambulance
25,10/08/2018,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996343,Box Truck,Sedan
26,10/08/2018,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,1,...,0,0,0,1,0,Turning Improperly,Unspecified,3996777,Sedan,Station Wagon/Sport Utility Vehicle
27,10/08/2018,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996177,Box Truck,Station Wagon/Sport Utility Vehicle
28,10/08/2018,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,3996251,Sedan,Sedan
29,10/08/2018,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,0,...,0,0,0,0,0,Unsafe Speed,Driver Inattention/Distraction,3996216,Sedan,Sedan
30,10/08/2018,10:30,NaN,NaN,40.806133,-73.961555,"(40.806133, -73.961555)",AMSTERDAM AVENUE,NaN,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3995919,Station Wagon/Sport Utility Vehicle,Taxi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360281,07/01/2012,8:00,BROOKLYN,11233,40.683160,-73.938078,"(40.6831597, -73.9380784)",HALSEY STREET,MARCUS GARVEY BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,182648,PASSENGER VEHICLE,PASSENGER VEHICLE
1360282,07/01/2012,8:00,QUEENS,11004,40.751826,-73.719206,"(40.7518264, -73.7192065)",LANGSTON AVENUE,260 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219397,PASSENGER VEHICLE,UNKNOWN
1360284,07/01/2012,8:07,MANHATTAN,10009,40.721678,-73.980605,"(40.7216783, -73.9806054)",EAST 3 STREET,AVENUE C,0,...,0,0,0,0,0,Illness,Unspecified,13868,TAXI,TAXI
1360285,07/01/2012,8:08,BROOKLYN,11233,40.672791,-73.922215,"(40.6727913, -73.9222153)",RALPH AVENUE,PROSPECT PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,172550,PASSENGER VEHICLE,PASSENGER VEHICLE
1360286,07/01/2012,8:15,QUEENS,11373,40.739979,-73.877108,"(40.7399795, -73.8771085)",87 STREET,CORONA AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,254993,PASSENGER VEHICLE,UNKNOWN
1360287,07/01/2012,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,179414,PASSENGER VEHICLE,LIVERY VEHICLE
1360290,07/01/2012,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,2,...,0,0,0,2,0,Unspecified,Unspecified,172551,PASSENGER VEHICLE,VAN
1360291,07/01/2012,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,1,...,0,0,0,0,0,Unspecified,NaN,208724,UNKNOWN,NaN
1360293,07/01/2012,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,94868,SPORT UTILITY / STATION WAGON,UNKNOWN
1360294,07/01/2012,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360295,07/01/2012,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,1,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,37634,TAXI,NaN
1360296,07/01/2012,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,0,...,0,0,0,0,0,Unspecified,Unspecified,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
1360297,07/01/2012,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,0,...,0,0,0,0,0,Failure to Keep Right,Unspecified,203690,PASSENGER VEHICLE,PASSENGER VEHICLE
1360298,07/01/2012,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,219394,PASSENGER VEHICLE,UNKNOWN
1360299,07/01/2012,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,284646,PASSENGER VEHICLE,PASSENGER VEHICLE
1360301,07/01/2012,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219398,PASSENGER VEHICLE,UNKNOWN
1360302,07/01/2012,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,0,...,0,0,0,0,0,Unspecified,Unspecified,88535,PASSENGER VEHICLE,UNKNOWN
1360303,07/01/2012,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,129899,PASSENGER VEHICLE,UNKNOWN
1360304,07/01/2012,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,254997,PASSENGER VEHICLE,PASSENGER VEHICLE
1360305,07/01/2012,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,1,...,0,0,0,1,0,Unspecified,Unspecified,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360306,07/01/2012,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360307,07/01/2012,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360308,07/01/2012,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,0,...,0,0,0,0,0,Driver Inexperience,Driver Inexperience,5294,PASSENGER VEHICLE,LIVERY VEHICLE
1360309,07/01/2012,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,245559,PASSENGER VEHICLE,PASSENGER VEHICLE
1360310,07/01/2012,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON
1360311,07/01/2012,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1360313,07/01/2012,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,37635,VAN,SPORT UTILITY / STATION WAGON
1360314,07/01/2012,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,0,...,0,0,0,0,0,View Obstructed/Limited,Unspecified,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1360315,07/01/2012,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,44907,PASSENGER VEHICLE,TAXI
1360316,07/01/2012,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,0,...,0,0,0,0,0,Glare,Unspecified,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON

### *Now we have reduced rows from 1360317 to 1130042* 


## Re-Indexing :
Conform DataFrame to new index with optional filling logic, placing NA/NaN in locations having no value in the previous index. A new object is produced unless the new index is equivalent to the current one and copy=False

In [116]:
data = data.reset_index(drop=True)

In [117]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,NUMBER OF PERSONS INJURED,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,10/08/2018,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996168,Sedan,Station Wagon/Sport Utility Vehicle
1,10/08/2018,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
2,10/08/2018,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,0,...,0,0,0,0,0,Other Vehicular,Unspecified,3997603,Sedan,Taxi
3,10/08/2018,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996194,Sedan,Sedan
4,10/08/2018,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,0,...,0,0,0,0,0,Following Too Closely,Unspecified,3995663,Taxi,Pick-up Truck
5,10/08/2018,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,1,...,0,0,0,1,0,Traffic Control Disregarded,Unsafe Speed,3996499,Sedan,Sedan
6,10/08/2018,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996010,Sedan,NaN
7,10/08/2018,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,1,...,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,3995363,Taxi,Bike
8,10/08/2018,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3996597,Station Wagon/Sport Utility Vehicle,Sedan
9,10/08/2018,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle
10,10/08/2018,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,0,...,0,0,0,0,0,Unspecified,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN
11,10/08/2018,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
12,10/08/2018,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3995721,Sedan,Taxi
13,10/08/2018,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995990,Sedan,NaN
14,10/08/2018,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3997540,Sedan,Sedan
15,10/08/2018,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997169,Station Wagon/Sport Utility Vehicle,Dump
16,10/08/2018,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN
17,10/08/2018,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3996058,Sedan,Sedan
18,10/08/2018,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3996567,Dump,Sedan
19,10/08/2018,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,1,...,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
20,10/08/2018,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,0,...,0,0,0,0,0,Reaction to Uninvolved Vehicle,Unspecified,3996206,Station Wagon/Sport Utility Vehicle,Sedan
21,10/08/2018,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,1,...,0,0,0,1,0,Following Too Closely,Unspecified,3996726,Sedan,Station Wagon/Sport Utility Vehicle
22,10/08/2018,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996522,Sedan,Sedan
23,10/08/2018,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,3995978,Sedan,Ambulance
24,10/08/2018,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996343,Box Truck,Sedan
25,10/08/2018,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,1,...,0,0,0,1,0,Turning Improperly,Unspecified,3996777,Sedan,Station Wagon/Sport Utility Vehicle
26,10/08/2018,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996177,Box Truck,Station Wagon/Sport Utility Vehicle
27,10/08/2018,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,3996251,Sedan,Sedan
28,10/08/2018,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,0,...,0,0,0,0,0,Unsafe Speed,Driver Inattention/Distraction,3996216,Sedan,Sedan
29,10/08/2018,10:30,NaN,NaN,40.806133,-73.961555,"(40.806133, -73.961555)",AMSTERDAM AVENUE,NaN,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3995919,Station Wagon/Sport Utility Vehicle,Taxi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130012,07/01/2012,8:00,BROOKLYN,11233,40.683160,-73.938078,"(40.6831597, -73.9380784)",HALSEY STREET,MARCUS GARVEY BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,182648,PASSENGER VEHICLE,PASSENGER VEHICLE
1130013,07/01/2012,8:00,QUEENS,11004,40.751826,-73.719206,"(40.7518264, -73.7192065)",LANGSTON AVENUE,260 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219397,PASSENGER VEHICLE,UNKNOWN
1130014,07/01/2012,8:07,MANHATTAN,10009,40.721678,-73.980605,"(40.7216783, -73.9806054)",EAST 3 STREET,AVENUE C,0,...,0,0,0,0,0,Illness,Unspecified,13868,TAXI,TAXI
1130015,07/01/2012,8:08,BROOKLYN,11233,40.672791,-73.922215,"(40.6727913, -73.9222153)",RALPH AVENUE,PROSPECT PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,172550,PASSENGER VEHICLE,PASSENGER VEHICLE
1130016,07/01/2012,8:15,QUEENS,11373,40.739979,-73.877108,"(40.7399795, -73.8771085)",87 STREET,CORONA AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,254993,PASSENGER VEHICLE,UNKNOWN
1130017,07/01/2012,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,179414,PASSENGER VEHICLE,LIVERY VEHICLE
1130018,07/01/2012,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,2,...,0,0,0,2,0,Unspecified,Unspecified,172551,PASSENGER VEHICLE,VAN
1130019,07/01/2012,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,1,...,0,0,0,0,0,Unspecified,NaN,208724,UNKNOWN,NaN
1130020,07/01/2012,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,94868,SPORT UTILITY / STATION WAGON,UNKNOWN
1130021,07/01/2012,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130022,07/01/2012,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,1,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,37634,TAXI,NaN
1130023,07/01/2012,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,0,...,0,0,0,0,0,Unspecified,Unspecified,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
1130024,07/01/2012,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,0,...,0,0,0,0,0,Failure to Keep Right,Unspecified,203690,PASSENGER VEHICLE,PASSENGER VEHICLE
1130025,07/01/2012,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,219394,PASSENGER VEHICLE,UNKNOWN
1130026,07/01/2012,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,284646,PASSENGER VEHICLE,PASSENGER VEHICLE
1130027,07/01/2012,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219398,PASSENGER VEHICLE,UNKNOWN
1130028,07/01/2012,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,0,...,0,0,0,0,0,Unspecified,Unspecified,88535,PASSENGER VEHICLE,UNKNOWN
1130029,07/01/2012,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,129899,PASSENGER VEHICLE,UNKNOWN
1130030,07/01/2012,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,254997,PASSENGER VEHICLE,PASSENGER VEHICLE
1130031,07/01/2012,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,1,...,0,0,0,1,0,Unspecified,Unspecified,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130032,07/01/2012,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130033,07/01/2012,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130034,07/01/2012,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,0,...,0,0,0,0,0,Driver Inexperience,Driver Inexperience,5294,PASSENGER VEHICLE,LIVERY VEHICLE
1130035,07/01/2012,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,245559,PASSENGER VEHICLE,PASSENGER VEHICLE
1130036,07/01/2012,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON
1130037,07/01/2012,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130038,07/01/2012,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,37635,VAN,SPORT UTILITY / STATION WAGON
1130039,07/01/2012,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,0,...,0,0,0,0,0,View Obstructed/Limited,Unspecified,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130040,07/01/2012,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,44907,PASSENGER VEHICLE,TAXI
1130041,07/01/2012,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,0,...,0,0,0,0,0,Glare,Unspecified,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON

## Date Parsing :
### In this we parse the date to the format of date as given date is of string format so that it is easy to perform date and time operations. i.e converting from 10/08/2018 to 2018-10-08

In [121]:
data['DATE'] = pd.to_datetime(data['DATE'])

In [122]:
data

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,NUMBER OF PERSONS INJURED,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,2018-10-08,0:00,BROOKLYN,11211,40.713074,-73.952095,"(40.713074, -73.952095)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996168,Sedan,Station Wagon/Sport Utility Vehicle
1,2018-10-08,0:00,BROOKLYN,11224,40.577908,-74.008180,"(40.577908, -74.00818)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996787,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
2,2018-10-08,0:00,MANHATTAN,10036,40.758680,-73.983360,"(40.75868, -73.98336)",NaN,NaN,0,...,0,0,0,0,0,Other Vehicular,Unspecified,3997603,Sedan,Taxi
3,2018-10-08,0:00,NaN,NaN,40.708324,-73.843140,"(40.708324, -73.84314)",JACKIE ROBINSON PKWY,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996194,Sedan,Sedan
4,2018-10-08,0:00,NaN,NaN,40.763428,-73.965220,"(40.763428, -73.96522)",NaN,NaN,0,...,0,0,0,0,0,Following Too Closely,Unspecified,3995663,Taxi,Pick-up Truck
5,2018-10-08,0:00,QUEENS,11435,40.700768,-73.810190,"(40.700768, -73.81019)",91 AVENUE,144 PLACE,1,...,0,0,0,1,0,Traffic Control Disregarded,Unsafe Speed,3996499,Sedan,Sedan
6,2018-10-08,0:01,NaN,NaN,40.704712,-73.727425,"(40.704712, -73.727425)",CROSS ISLAND PARKWAY,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996010,Sedan,NaN
7,2018-10-08,0:10,MANHATTAN,10013,40.724564,-74.007790,"(40.724564, -74.00779)",HUDSON STREET,BROOME STREET,1,...,0,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,3995363,Taxi,Bike
8,2018-10-08,0:15,BRONX,10469,40.871810,-73.855560,"(40.87181, -73.85556)",BOSTON ROAD,LACONIA AVENUE,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3996597,Station Wagon/Sport Utility Vehicle,Sedan
9,2018-10-08,0:17,NaN,NaN,40.706944,-73.917740,"(40.706944, -73.91774)",HART STREET,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3995713,Pick-up Truck,Station Wagon/Sport Utility Vehicle
10,2018-10-08,0:25,MANHATTAN,10006,40.710114,-74.012665,"(40.710114, -74.012665)",GREENWICH STREET,LIBERTY STREET,0,...,0,0,0,0,0,Unspecified,NaN,3995878,Station Wagon/Sport Utility Vehicle,NaN
11,2018-10-08,0:30,BRONX,10472,40.831287,-73.881730,"(40.831287, -73.88173)",EAST 172 STREET,BRONX RIVER AVENUE,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
12,2018-10-08,0:30,MANHATTAN,10027,40.807960,-73.949080,"(40.80796, -73.94908)",NaN,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3995721,Sedan,Taxi
13,2018-10-08,0:30,NaN,NaN,40.716030,-73.816370,"(40.71603, -73.81637)",GRAND CENTRAL PARKWAY,141 STREET,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3995990,Sedan,NaN
14,2018-10-08,0:44,BROOKLYN,11201,40.691586,-73.999270,"(40.691586, -73.99927)",BROOKLYN QNS EXPRESSWAY,ATLANTIC AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3997540,Sedan,Sedan
15,2018-10-08,0:44,NaN,NaN,40.753513,-73.988790,"(40.753513, -73.98879)",7 AVENUE,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997169,Station Wagon/Sport Utility Vehicle,Dump
16,2018-10-08,0:45,QUEENS,11355,40.740173,-73.811264,"(40.740173, -73.811264)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,NaN,3995347,Station Wagon/Sport Utility Vehicle,NaN
17,2018-10-08,10:00,NaN,NaN,40.766434,-73.837670,"(40.766434, -73.83767)",32 AVENUE,COLLEGE POINT BOULEVARD,0,...,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,3996058,Sedan,Sedan
18,2018-10-08,10:00,NaN,NaN,40.592846,-73.796160,"(40.592846, -73.79616)",BEACH CHANNEL DRIVE,NaN,0,...,0,0,0,0,0,Turning Improperly,Unspecified,3996567,Dump,Sedan
19,2018-10-08,10:00,NaN,NaN,40.716957,-73.826550,"(40.716957, -73.82655)",VAN WYCK EXPWY,NaN,1,...,0,0,0,1,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3997076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
20,2018-10-08,10:15,NaN,NaN,40.764587,-73.904520,"(40.764587, -73.90452)",49 STREET,NaN,0,...,0,0,0,0,0,Reaction to Uninvolved Vehicle,Unspecified,3996206,Station Wagon/Sport Utility Vehicle,Sedan
21,2018-10-08,10:15,NaN,NaN,40.860600,-73.911020,"(40.8606, -73.91102)",WEST 183 STREET,NaN,1,...,0,0,0,1,0,Following Too Closely,Unspecified,3996726,Sedan,Station Wagon/Sport Utility Vehicle
22,2018-10-08,10:16,MANHATTAN,10029,40.788580,-73.955284,"(40.78858, -73.955284)",EAST 97 STREET,5 AVENUE,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,3996522,Sedan,Sedan
23,2018-10-08,10:25,BRONX,10473,40.822086,-73.851906,"(40.822086, -73.851906)",OLMSTEAD AVENUE,VIRGIL PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,3995978,Sedan,Ambulance
24,2018-10-08,10:29,NaN,NaN,40.663315,-73.989770,"(40.663315, -73.98977)",PROSPECT EXPRESSWAY EAST,NaN,0,...,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,3996343,Box Truck,Sedan
25,2018-10-08,10:29,NaN,NaN,40.859850,-73.935520,"(40.85985, -73.93552)",HENRY HUDSON PARKWAY,NaN,1,...,0,0,0,1,0,Turning Improperly,Unspecified,3996777,Sedan,Station Wagon/Sport Utility Vehicle
26,2018-10-08,10:30,BROOKLYN,11204,40.633500,-73.980520,"(40.6335, -73.98052)",NaN,NaN,0,...,0,0,0,0,0,Unspecified,Unspecified,3996177,Box Truck,Station Wagon/Sport Utility Vehicle
27,2018-10-08,10:30,QUEENS,11373,40.740402,-73.887100,"(40.740402, -73.8871)",46 AVENUE,78 STREET,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,3996251,Sedan,Sedan
28,2018-10-08,10:30,QUEENS,11418,40.699290,-73.831540,"(40.69929, -73.83154)",NaN,NaN,0,...,0,0,0,0,0,Unsafe Speed,Driver Inattention/Distraction,3996216,Sedan,Sedan
29,2018-10-08,10:30,NaN,NaN,40.806133,-73.961555,"(40.806133, -73.961555)",AMSTERDAM AVENUE,NaN,0,...,0,0,0,0,0,Driver Inexperience,Unspecified,3995919,Station Wagon/Sport Utility Vehicle,Taxi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130012,2012-07-01,8:00,BROOKLYN,11233,40.683160,-73.938078,"(40.6831597, -73.9380784)",HALSEY STREET,MARCUS GARVEY BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,182648,PASSENGER VEHICLE,PASSENGER VEHICLE
1130013,2012-07-01,8:00,QUEENS,11004,40.751826,-73.719206,"(40.7518264, -73.7192065)",LANGSTON AVENUE,260 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219397,PASSENGER VEHICLE,UNKNOWN
1130014,2012-07-01,8:07,MANHATTAN,10009,40.721678,-73.980605,"(40.7216783, -73.9806054)",EAST 3 STREET,AVENUE C,0,...,0,0,0,0,0,Illness,Unspecified,13868,TAXI,TAXI
1130015,2012-07-01,8:08,BROOKLYN,11233,40.672791,-73.922215,"(40.6727913, -73.9222153)",RALPH AVENUE,PROSPECT PLACE,0,...,0,0,0,0,0,Unspecified,Unspecified,172550,PASSENGER VEHICLE,PASSENGER VEHICLE
1130016,2012-07-01,8:15,QUEENS,11373,40.739979,-73.877108,"(40.7399795, -73.8771085)",87 STREET,CORONA AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,254993,PASSENGER VEHICLE,UNKNOWN
1130017,2012-07-01,8:27,BROOKLYN,11216,40.680857,-73.938546,"(40.6808571, -73.9385457)",DECATUR STREET,ALBANY AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,179414,PASSENGER VEHICLE,LIVERY VEHICLE
1130018,2012-07-01,8:34,BROOKLYN,11213,40.668798,-73.931120,"(40.6687978, -73.9311201)",EASTERN PARKWAY,UTICA AVENUE,2,...,0,0,0,2,0,Unspecified,Unspecified,172551,PASSENGER VEHICLE,VAN
1130019,2012-07-01,8:37,QUEENS,11435,40.694545,-73.802112,"(40.6945453, -73.802112)",SOUTH ROAD,SUTPHIN BOULEVARD,1,...,0,0,0,0,0,Unspecified,NaN,208724,UNKNOWN,NaN
1130020,2012-07-01,8:58,BRONX,10466,40.891840,-73.862740,"(40.8918398, -73.8627401)",BRONX BOULEVARD,EAST 229 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,94868,SPORT UTILITY / STATION WAGON,UNKNOWN
1130021,2012-07-01,9:00,QUEENS,11101,40.744131,-73.927047,"(40.7441309, -73.9270473)",38 STREET,QUEENS BOULEVARD,0,...,0,0,0,0,0,Unspecified,Unspecified,238643,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130022,2012-07-01,9:00,MANHATTAN,10022,40.757859,-73.975592,"(40.7578587, -73.975592)",EAST 50 STREET,MADISON AVENUE,1,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,37634,TAXI,NaN
1130023,2012-07-01,9:15,BROOKLYN,11233,40.675380,-73.908196,"(40.6753803, -73.9081956)",PACIFIC STREET,EASTERN PARKWAY,0,...,0,0,0,0,0,Unspecified,Unspecified,160103,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
1130024,2012-07-01,9:15,QUEENS,11421,40.696308,-73.851549,"(40.6963077, -73.8515486)",94 STREET,85 ROAD,0,...,0,0,0,0,0,Failure to Keep Right,Unspecified,203690,PASSENGER VEHICLE,PASSENGER VEHICLE
1130025,2012-07-01,9:15,QUEENS,11429,40.711860,-73.735538,"(40.7118601, -73.7355383)",219 STREET,104 AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,219394,PASSENGER VEHICLE,UNKNOWN
1130026,2012-07-01,9:15,STATEN ISLAND,10310,40.634748,-74.112253,"(40.6347476, -74.1122528)",CASTLETON AVENUE,BEMENT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,284646,PASSENGER VEHICLE,PASSENGER VEHICLE
1130027,2012-07-01,9:24,QUEENS,11411,40.690917,-73.728179,"(40.6909168, -73.7281786)",LINDEN BOULEVARD,234 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,219398,PASSENGER VEHICLE,UNKNOWN
1130028,2012-07-01,9:30,BRONX,10475,40.861637,-73.824326,"(40.8616372, -73.8243256)",HUNTER AVENUE,EARHART LANE,0,...,0,0,0,0,0,Unspecified,Unspecified,88535,PASSENGER VEHICLE,UNKNOWN
1130029,2012-07-01,9:30,BROOKLYN,11219,40.626826,-73.996790,"(40.626826, -73.9967902)",61 STREET,NEW UTRECHT AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,129899,PASSENGER VEHICLE,UNKNOWN
1130030,2012-07-01,9:30,QUEENS,11368,40.755336,-73.843245,"(40.7553365, -73.8432452)",ROOSEVELT AVENUE,126 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,254997,PASSENGER VEHICLE,PASSENGER VEHICLE
1130031,2012-07-01,9:30,BROOKLYN,11207,40.678163,-73.897477,"(40.6781627, -73.8974769)",JAMAICA AVENUE,PENNSYLVANIA AVENUE,1,...,0,0,0,1,0,Unspecified,Unspecified,163374,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130032,2012-07-01,9:39,BROOKLYN,11226,40.646518,-73.958105,"(40.6465177, -73.958105)",TILDEN AVENUE,FLATBUSH AVENUE,0,...,0,0,0,0,0,Unspecified,Unspecified,147454,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130033,2012-07-01,9:40,BRONX,10462,40.839882,-73.857658,"(40.8398819, -73.8576576)",METROPOLITAN AVENUE,MAPLE DRIVE,0,...,0,0,0,0,0,Backing Unsafely,Unspecified,80827,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130034,2012-07-01,9:40,MANHATTAN,10002,40.714069,-73.997504,"(40.7140687, -73.9975038)",DIVISION STREET,CATHERINE STREET,0,...,0,0,0,0,0,Driver Inexperience,Driver Inexperience,5294,PASSENGER VEHICLE,LIVERY VEHICLE
1130035,2012-07-01,9:40,QUEENS,11354,40.764455,-73.831773,"(40.7644548, -73.831773)",35 AVENUE,FARRINGTON STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,245559,PASSENGER VEHICLE,PASSENGER VEHICLE
1130036,2012-07-01,9:40,QUEENS,11369,40.767470,-73.881859,"(40.7674704, -73.8818593)",23 AVENUE,88 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279641,PICK-UP TRUCK,SPORT UTILITY / STATION WAGON
1130037,2012-07-01,9:40,QUEENS,11370,40.758743,-73.890690,"(40.7587426, -73.8906895)",31 AVENUE,77 STREET,0,...,0,0,0,0,0,Unspecified,Unspecified,279639,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE
1130038,2012-07-01,9:50,MANHATTAN,10019,40.766779,-73.996762,"(40.7667789, -73.9967618)",WEST SIDE HIGHWAY,WEST 50 STREET,0,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,37635,VAN,SPORT UTILITY / STATION WAGON
1130039,2012-07-01,9:50,QUEENS,11001,40.736245,-73.702966,"(40.7362448, -73.7029656)",265 STREET,85 AVENUE,0,...,0,0,0,0,0,View Obstructed/Limited,Unspecified,219395,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
1130040,2012-07-01,9:57,MANHATTAN,10065,40.765242,-73.957868,"(40.7652424, -73.9578679)",1 AVENUE,EAST 68 STREET,0,...,0,0,0,0,0,Other Vehicular,Other Vehicular,44907,PASSENGER VEHICLE,TAXI
1130041,2012-07-01,9:59,BRONX,10452,40.835397,-73.920305,"(40.835397, -73.920305)",EAST 167 STREET,GERARD AVENUE,0,...,0,0,0,0,0,Glare,Unspecified,85154,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON